# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/wayne/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/wayne

PRODUCT_COPY_FILES += \
    vendor/xiaomi/wayne/proprietary/vendor/etc/MIUI_DualCamera_watermark.png:$(TARGET_COPY_OUT_VENDOR)/etc/MIUI_DualCamera_watermark.png
