# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/jasmine_sprout/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),jasmine_sprout)

endif
