# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/msm8996-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter capricorn gemini lithium natrium scorpio,$(TARGET_DEVICE)),)

endif
