# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/wayne-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter jasmine_sprout wayne,$(TARGET_DEVICE)),)

endif
